"""The LLM-agent layer: a retrieval-augmented (RAG) "preliminary findings" note
generated by Claude on Amazon Bedrock.

Pipeline
--------
1. The image classifier produces a label + probability vector.
2. Grad-CAM produces a coarse region description (`gradcam.describe_cam`).
3. We embed that context + the dataset topic with Amazon Titan Embeddings, retrieve
   the top-k matching snippets from the curated clinical knowledge base
   (`knowledge_base/*.json`) via FAISS, and
4. ask Claude to write a short, structured, explicitly NON-diagnostic note that cites
   only the retrieved snippets and surfaces the model's uncertainty.

Everything degrades gracefully:
  * no boto3 / no AWS creds  -> a clearly-labelled offline template report.
  * no faiss               -> brute-force cosine search over cached embeddings.

Nothing here persists patient data; inputs are processed in memory.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Optional

import numpy as np

from .config import BedrockConfig, KB_DIR, FAISS_DIR


# --------------------------------------------------------------------------- #
# Knowledge base loading + embedding index
# --------------------------------------------------------------------------- #
def _load_kb() -> list[dict]:
    docs: list[dict] = []
    for path in sorted(KB_DIR.glob("*.json")):
        docs.extend(json.loads(path.read_text(encoding="utf-8")))
    return docs


@dataclass
class _Index:
    docs: list[dict]
    embeddings: np.ndarray         # (N, D), L2-normalised
    faiss_index: object = None     # faiss.IndexFlatIP or None


class ClinicalKB:
    """Builds (and caches) a small vector index over the curated reference snippets."""

    def __init__(self, bedrock_cfg: BedrockConfig, client=None):
        self.cfg = bedrock_cfg
        self.client = client
        self.docs = _load_kb()
        self._index: Optional[_Index] = None

    # -- embedding via Titan, with a deterministic offline fallback -----------
    def _embed(self, texts: list[str]) -> np.ndarray:
        if self.client is not None:
            vecs = []
            for t in texts:
                body = json.dumps({"inputText": t})
                resp = self.client.invoke_model(modelId=self.cfg.embed_model_id, body=body)
                payload = json.loads(resp["body"].read())
                vecs.append(payload["embedding"])
            arr = np.asarray(vecs, dtype=np.float32)
        else:
            # Offline fallback: hashed bag-of-words "embedding". Not semantically great,
            # but deterministic and keeps the demo runnable without AWS. Clearly a stand-in.
            arr = np.stack([_hashing_embed(t) for t in texts]).astype(np.float32)
        # L2-normalise so inner product == cosine similarity
        norms = np.linalg.norm(arr, axis=1, keepdims=True)
        return arr / np.clip(norms, 1e-8, None)

    def build(self) -> "ClinicalKB":
        texts = [f"{d['title']}. {d['text']}" for d in self.docs]
        emb = self._embed(texts)
        faiss_index = None
        try:
            import faiss
            faiss_index = faiss.IndexFlatIP(emb.shape[1])
            faiss_index.add(emb)
        except Exception:
            faiss_index = None
        self._index = _Index(self.docs, emb, faiss_index)
        return self

    def retrieve(self, query: str, k: Optional[int] = None) -> list[dict]:
        if self._index is None:
            self.build()
        k = k or self.cfg.top_k_passages
        q = self._embed([query])[0]
        idx = self._index
        if idx.faiss_index is not None:
            scores, ids = idx.faiss_index.search(q[None, :], min(k, len(idx.docs)))
            order = ids[0]
            sims = scores[0]
        else:
            sims_all = idx.embeddings @ q
            order = np.argsort(-sims_all)[:k]
            sims = sims_all[order]
        out = []
        for rank, (i, s) in enumerate(zip(order, sims)):
            d = dict(idx.docs[int(i)])
            d["_score"] = float(s)
            d["_rank"] = rank + 1
            out.append(d)
        return out


def _hashing_embed(text: str, dim: int = 512) -> np.ndarray:
    """Tiny deterministic offline embedding: hashed unigram counts. Stand-in only."""
    v = np.zeros(dim, dtype=np.float32)
    for tok in text.lower().split():
        tok = "".join(ch for ch in tok if ch.isalnum())
        if not tok:
            continue
        v[hash(tok) % dim] += 1.0
    return v


# --------------------------------------------------------------------------- #
# Bedrock client
# --------------------------------------------------------------------------- #
def make_bedrock_client(cfg: BedrockConfig):
    """Return a bedrock-runtime client, or None if AWS isn't configured here."""
    try:
        import boto3
        client = boto3.client("bedrock-runtime", region_name=cfg.region)
        return client
    except Exception as e:  # noqa: BLE001 - we genuinely want to fall back on anything
        print(f"[bedrock] not available ({e!r}); using offline template report.")
        return None


# --------------------------------------------------------------------------- #
# Prompt construction
# --------------------------------------------------------------------------- #
SYSTEM_PROMPT = """You are a careful clinical-documentation assistant inside an EDUCATIONAL demo \
called "MedScan + Explain". You are NOT a doctor and you do NOT diagnose. You write a short, \
structured PRELIMINARY note that:
- explicitly states it is an automated, non-diagnostic educational output;
- reports the image classifier's prediction and its confidence in plain language, including the \
fact that a softmax probability is a calibration-unaware confidence, not a probability of disease;
- summarises the Grad-CAM region description as "where the model looked", clearly labelled coarse;
- uses ONLY the provided reference snippets for any clinical statements, and cites them by their \
bracketed id (e.g. [cxr-pneumonia-consolidation]); never invent facts or sources;
- lists concrete next steps that route to a qualified clinician;
- ends with a one-line disclaimer.
Keep it under ~250 words. Use short labelled sections. Never output a definitive diagnosis, \
prognosis, drug dose, or anything that could be acted on without a clinician."""


def _build_user_prompt(*, dataset: str, class_names: list[str], pred_idx: int,
                       probs: np.ndarray, cam_description: str, patient_meta: dict,
                       snippets: list[dict]) -> str:
    prob_lines = "\n".join(
        f"  - {name}: {p:.1%}" for name, p in zip(class_names, probs)
    )
    refs = "\n".join(
        f"[{s['id']}] {s['title']} :: {s['text']} (source: {s.get('source','n/a')})"
        for s in snippets
    )
    meta = ", ".join(f"{k}={v}" for k, v in patient_meta.items()) or "none provided"
    return f"""DATASET / TASK: {dataset}
CLASSIFIER PREDICTION: {class_names[pred_idx]}
CLASS PROBABILITIES:
{prob_lines}
GRAD-CAM REGION DESCRIPTION (coarse): {cam_description}
PATIENT METADATA (synthetic/de-identified): {meta}

RETRIEVED CLINICAL REFERENCE SNIPPETS (cite by [id] only — do not use outside knowledge):
{refs}

Write the preliminary educational note now."""


# --------------------------------------------------------------------------- #
# Public entry point
# --------------------------------------------------------------------------- #
def generate_report(*, dataset: str, class_names: list[str], pred_idx: int,
                    probs, cam_description: str, patient_meta: Optional[dict] = None,
                    bedrock_cfg: Optional[BedrockConfig] = None,
                    kb: Optional[ClinicalKB] = None) -> dict:
    """Produce the structured preliminary note. Returns a dict with the text + provenance."""
    probs = np.asarray(probs, dtype=np.float64).ravel()
    patient_meta = patient_meta or {}
    cfg = bedrock_cfg or BedrockConfig()

    client = (kb.client if kb is not None else None) or make_bedrock_client(cfg)
    kb = kb or ClinicalKB(cfg, client=client).build()

    # retrieval query: the prediction + grad-cam description biases toward the right topic
    query = f"{dataset} {class_names[pred_idx]} {cam_description}"
    snippets = kb.retrieve(query, k=cfg.top_k_passages)

    user_prompt = _build_user_prompt(
        dataset=dataset, class_names=class_names, pred_idx=pred_idx, probs=probs,
        cam_description=cam_description, patient_meta=patient_meta, snippets=snippets,
    )

    if client is not None:
        text = _invoke_claude(client, cfg, user_prompt)
        backend = f"bedrock:{cfg.chat_model_id}"
    else:
        text = _offline_template(dataset, class_names, pred_idx, probs, cam_description, snippets)
        backend = "offline-template"

    return {
        "report": text,
        "backend": backend,
        "retrieved": [{"id": s["id"], "rank": s["_rank"], "score": round(s["_score"], 4)}
                      for s in snippets],
        "prediction": {"label": class_names[pred_idx],
                       "probabilities": {n: float(p) for n, p in zip(class_names, probs)}},
    }


def _invoke_claude(client, cfg: BedrockConfig, user_prompt: str) -> str:
    body = {
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens": cfg.max_tokens,
        "temperature": cfg.temperature,
        "system": SYSTEM_PROMPT,
        "messages": [{"role": "user", "content": [{"type": "text", "text": user_prompt}]}],
    }
    resp = client.invoke_model(modelId=cfg.chat_model_id, body=json.dumps(body))
    payload = json.loads(resp["body"].read())
    # messages API: content is a list of blocks
    return "".join(block.get("text", "") for block in payload.get("content", [])).strip()


def _offline_template(dataset, class_names, pred_idx, probs, cam_description, snippets) -> str:
    conf = probs[pred_idx]
    cites = " ".join(f"[{s['id']}]" for s in snippets[:3])
    return f"""**PRELIMINARY EDUCATIONAL NOTE — AUTOMATED, NOT A DIAGNOSIS**
*(Generated offline without an LLM because AWS Bedrock was not configured in this environment.)*

**Task:** {dataset}
**Model prediction:** {class_names[pred_idx]} (model confidence ~ {conf:.0%}).
Note: this percentage is an uncalibrated softmax score, not a probability of disease.

**Where the model looked (coarse):** {cam_description}

**Relevant background (from the curated knowledge base):** {cites}
{chr(10).join('- ' + s['title'] + ': ' + s['text'] for s in snippets[:3])}

**Suggested next steps:** Treat this output as a study aid only. Any real concern about
symptoms or a lesion/film should be reviewed in person by a qualified clinician, who can
take a history, examine the patient, and order appropriate tests.

*Disclaimer: MedScan + Explain is a course project. It is not a medical device and must not
be used for diagnosis or treatment decisions.*"""


# --------------------------------------------------------------------------- #
# CLI smoke test (no GPU / no AWS needed): python -m src.bedrock_report
# --------------------------------------------------------------------------- #
if __name__ == "__main__":
    demo = generate_report(
        dataset="pneumonia",
        class_names=["NORMAL", "PNEUMONIA"],
        pred_idx=1,
        probs=[0.18, 0.82],
        cam_description="Grad-CAM indicates model attention concentrated in the lower-right "
                        "region(s) of the image for the 'PNEUMONIA' prediction. This is a coarse heat-map.",
        patient_meta={"age_group": "pediatric", "view": "AP"},
    )
    print(f"backend: {demo['backend']}")
    print(f"retrieved: {demo['retrieved']}\n")
    # write to stdout defensively: some Windows consoles are cp1252 and can't encode
    # the emoji/dashes an LLM may emit. Replace un-encodable chars rather than crashing.
    import sys
    enc = sys.stdout.encoding or "utf-8"
    sys.stdout.write(demo["report"].encode(enc, errors="replace").decode(enc) + "\n")
